#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Rokort_Android.Resource", IsApplication=true)]

namespace Rokort_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int spinner_boats_array = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int spinner_rower_names_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060005
			public const int editTextDistance = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int myButton = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int spinnerBoats = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int spinnerRowerNames = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int start_trip_wrapper = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int stop_trip_wrapper = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int textViewDistanceLabel = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int boats_prompt = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int button_disabled_text = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int distance_unit_hint = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int rower_names_prompt = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int start_trip = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int stop_trip = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
